### ISSUE TITLE
Error downloading directory

### ISSUE THREAD

**Issue by torbenlu** [unioslo/tsd-api-client#100]
When trying to download a directory using --download-sync (or --download ) I get an error "NameError: name 'public_key' is not defined", see below. I can fix this locally by changing the offending line (line 527) in sync.py from public_key=public_key to public_key=self.public_key

```
$ tacl --version
tacl v3.5.2
- OS/Arch: Linux/x86_64
- Python: 3.6.8    

$ tacl pXXX --download-sync Test --cache-sync
fetching information about directory: Test
Traceback (most recent call last):
  File "/uio/platon/med-klinmed-u1/torbenlu/.local/bin/tacl", line 11, in <module>
    sys.exit(cli())
  File "/uio/platon/med-klinmed-u1/torbenlu/.local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/uio/platon/med-klinmed-u1/torbenlu/.local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/uio/platon/med-klinmed-u1/torbenlu/.local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/uio/platon/med-klinmed-u1/torbenlu/.local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/uio/platon/med-klinmed-u1/torbenlu/.local/lib/python3.6/site-packages/tsdapiclient/tacl.py", line 736, in cli
    syncer.sync()
  File "/uio/platon/med-klinmed-u1/torbenlu/.local/lib/python3.6/site-packages/tsdapiclient/sync.py", line 306, in sync
    self._transfer(resource, integrity_reference=integrity_reference)
  File "/uio/platon/med-klinmed-u1/torbenlu/.local/lib/python3.6/site-packages/tsdapiclient/sync.py", line 752, in _transfer
    resource, integrity_reference=integrity_reference
  File "/uio/platon/med-klinmed-u1/torbenlu/.local/lib/python3.6/site-packages/tsdapiclient/sync.py", line 527, in _transfer_remote_to_local
    public_key=public_key,
NameError: name 'public_key' is not defined
```

**Comment by haatveit** [comment]
Thank you very much for the bug report, this issue will be corrected.

-- 
Regards,

Eirik Haatveit
Research Services (FT/USIT)
Services for sensitive data (TSD)
University of Oslo
