### ISSUE TITLE
v1.8.3: Error message after running `tacl --resume-delete-all`

### ISSUE THREAD

**Issue by tinavisnovska** [unioslo/tsd-api-client#17]
Hi, this is all I can get from that command:

Traceback (most recent call last):
  File "/usr/local/bin/tacl_data", line 4, in <module>
    __import__('pkg_resources').run_script('tsd-api-client==1.8.3', 'tacl_data')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/tsd_api_client-1.8.3-py2.7.egg/EGG-INFO/scripts/tacl_data", line 312, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tsd_api_client-1.8.3-py2.7.egg/EGG-INFO/scripts/tacl_data", line 293, in main
    
  File "build/bdist.linux-x86_64/egg/tsdapiclient/fileapi.py", line 531, in delete_all_resumables
  File "build/bdist.linux-x86_64/egg/tsdapiclient/fileapi.py", line 507, in delete_resumable
  File "/usr/local/lib/python2.7/dist-packages/requests-2.22.0-py2.7.egg/requests/api.py", line 158, in delete
    return request('delete', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.22.0-py2.7.egg/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.22.0-py2.7.egg/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.22.0-py2.7.egg/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests-2.22.0-py2.7.egg/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.22.0-py2.7.egg/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'files': No schema supplied. Perhaps you meant http://files?

**Comment by haatveit** [comment]
Hi, thanks for reporting this bug. It should be resolved in 978230f.

**Comment by tinavisnovska** [comment]
Great, thanks!
