### ISSUE TITLE
tacl --export <filename> returns KeyError: 'etag' 

### ISSUE THREAD

**Issue by ofrei** [unioslo/tsd-api-client#22]
```
(python2) [oleksanf@login-nird-3 tsd-api-client]$ tacl --export checksums-ofrei.7z
User > p33-ofrei
Password > 
OTP > 007260
Traceback (most recent call last):
  File "/nird/home/oleksanf/miniconda3/envs/python2/bin/tacl_data", line 4, in <module>
    __import__('pkg_resources').run_script('tsd-api-client==1.8.3', 'tacl_data')
  File "/nird/home/oleksanf/miniconda3/envs/python2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/nird/home/oleksanf/miniconda3/envs/python2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/nird/home/oleksanf/miniconda3/envs/python2/lib/python2.7/site-packages/tsd_api_client-1.8.3-py2.7.egg/EGG-INFO/scripts/tacl_data", line 312, in <module>
    
  File "/nird/home/oleksanf/miniconda3/envs/python2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nird/home/oleksanf/miniconda3/envs/python2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nird/home/oleksanf/miniconda3/envs/python2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nird/home/oleksanf/miniconda3/envs/python2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nird/home/oleksanf/miniconda3/envs/python2/lib/python2.7/site-packages/tsd_api_client-1.8.3-py2.7.egg/EGG-INFO/scripts/tacl_data", line 282, in main
    
  File "build/bdist.linux-x86_64/egg/tsdapiclient/fileapi.py", line 235, in export_get
  File "/nird/home/oleksanf/miniconda3/envs/python2/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'etag'
```

**Comment by leondutoit** [comment]
I'll try to reproduce this.

**Comment by leondutoit** [comment]
I think this _might_ be because an intermediate proxy is stripping the etag header. If that is the case then resumable download will not work, but a once-off download should work. Can you please try again with the latest version of the client? btw, I've updated it to python3, so there _might_ be a breaking change with existing client config, which may mean having to delete the .tacl_config file, and re-registering the client.
