### ISSUE TITLE
tacl --export-list returns error

### ISSUE THREAD

**Issue by oskarvid** [unioslo/tsd-api-client#32]
I tried to list which files are available for export, I'm pretty sure I don't have export rights so perhaps that's why I'm getting this error?
```
user@hostname:~$ tacl --export-list
User > p11-ovi004
Password > 
OTP > 432849
Traceback (most recent call last):
  File "/usr/local/bin/tacl_data", line 4, in <module>
    __import__('pkg_resources').run_script('tsd-api-client==2.1.0', 'tacl_data')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/tsd_api_client-2.1.0-py3.5.egg/EGG-INFO/scripts/tacl_data", line 314, in <module>
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tsd_api_client-2.1.0-py3.5.egg/EGG-INFO/scripts/tacl_data", line 279, in main
  File "/usr/local/lib/python3.5/dist-packages/tsd_api_client-2.1.0-py3.5.egg/tsdapiclient/fileapi.py", line 195, in export_list
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by haatveit** [comment]
A case definitely could be made for improving the output here, but the error is a result of you not having export rights in p11.

**Comment by oskarvid** [comment]
Right, a user that does not know they don't have export rights would not understand what the issue is so an informative error message would help.

**Comment by haatveit** [comment]
Good point, and shouldn't be much work to implement. I'll have a look at it.
