### ISSUE TITLE
export-list AttributeError: module 'humanfriendly' has no attribute 'tables'

### ISSUE THREAD

**Issue by amundhb** [unioslo/tsd-api-client#43]
Running the most recent version of tsd-api-client (2.2.2) and version 8.1 of humanfriendly produces the following error:

```
[21:35:03] (base) user@hostname:~$ tacl --export-list
User > pxx-user
Password >
OTP > 929249
Traceback (most recent call last):
  File "/home/user/anaconda3/bin/tacl_data", line 4, in <module>
    __import__('pkg_resources').run_script('tsd-api-client==2.2.2', 'tacl_data')
  File "/home/user/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "/home/user/anaconda3/lib/python3.7/site-packages/tsd_api_client-2.2.2-py3.7.egg/EGG-INFO/scripts/tacl_data", line 340, in <module>
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/tsd_api_client-2.2.2-py3.7.egg/EGG-INFO/scripts/tacl_data", line 306, in main
  File "/home/user/anaconda3/lib/python3.7/site-packages/tsd_api_client-2.2.2-py3.7.egg/tsdapiclient/fileapi.py", line 179, in print_export_list
  File "/home/user/anaconda3/lib/python3.7/site-packages/humanfriendly/deprecation.py", line 240, in __getattr__
    raise AttributeError(format("module '%s' has no attribute '%s'", self.module.__name__, name))
AttributeError: module 'humanfriendly' has no attribute 'tables'
```

Downgrading humanfriendly to 7.1.1 fixes the issue.

**Comment by haatveit** [comment]
Thank you very much for letting us know! 👍
