### ISSUE TITLE
tacl download error

### ISSUE THREAD

**Issue by aksenia** [unioslo/tsd-api-client#75]
Fail to download file from TSD using tacl. userid and project anonymised. 

```
tacl pxx --download schedule.sh
Download id: xxx....
Traceback (most recent call last):
  File "/home/myuser/.local/bin/tacl", line 11, in <module>
    sys.exit(cli())
  File "/home/myuser/.local/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/myuser/.local/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/myuser/.local/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/myuser/.local/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/myuser/.local/lib/python3.6/site-packages/tsdapiclient/tacl.py", line 558, in cli
    export_get(env, pnum, filename, token, etag=download_id)
  File "/home/myuser/.local/lib/python3.6/site-packages/tsdapiclient/tools.py", line 136, in decorator
    return f(*args, **kwargs)
  File "/home/myuser/.local/lib/python3.6/site-packages/tsdapiclient/fileapi.py", line 437, in export_get
    os.makedirs(destination_dir)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by leondutoit** [comment]
Hi, I found the issue and will release a fix asap. Thanks for reporting.

**Comment by leondutoit** [comment]
@aksenia `pip3 install tsd-api-client --upgrade` should fix it.

**Comment by aksenia** [comment]
Hi! thanks for looking into it. Installed the upgrade. The error message persists though. I am not a root on the server, if this may be of significance.

**Comment by leondutoit** [comment]
I cannot reproduce the error anymore:
```
ldt:~ leondutoit$ pip3 install tsd-api-client --upgrade
Requirement already satisfied: tsd-api-client in /usr/local/lib/python3.9/site-packages/tsd_api_client-3.4.3-py3.9.egg (3.4.3)
Collecting tsd-api-client
  Downloading tsd_api_client-3.4.4-py3-none-any.whl (26 kB)
Requirement already satisfied: progress in /usr/local/lib/python3.9/site-packages (from tsd-api-client) (1.5)
Requirement already satisfied: requests in /usr/local/lib/python3.9/site-packages (from tsd-api-client) (2.25.1)
Requirement already satisfied: humanfriendly in /usr/local/lib/python3.9/site-packages (from tsd-api-client) (4.18)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.9/site-packages (from tsd-api-client) (5.1.2)
Requirement already satisfied: click in /usr/local/lib/python3.9/site-packages (from tsd-api-client) (8.0.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests->tsd-api-client) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests->tsd-api-client) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests->tsd-api-client) (2.8)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.9/site-packages (from requests->tsd-api-client) (3.0.4)
Installing collected packages: tsd-api-client
  Attempting uninstall: tsd-api-client
    Found existing installation: tsd-api-client 3.4.3
    Uninstalling tsd-api-client-3.4.3:
      Successfully uninstalled tsd-api-client-3.4.3
Successfully installed tsd-api-client-3.4.4
ldt:~ leondutoit$ tacl p11 --download mycap.pcap
your session has expired, please authenticate
username > p11-leoncd
password >
one time code > 691654
Download id: 19f0322aa14d97abee183611a9c77f03
mycap.pcap |################################| 100%
```

What does `tacl --version` say?

**Comment by aksenia** [comment]
`tacl v3.4.3
- OS/Arch: Linux/x86_64
- Python: 3.6.8`

**Comment by leondutoit** [comment]
Yeah you need version `3.4.4`.

**Comment by aksenia** [comment]
Did the upgrade with `--force` flag and now it works as expected. Thank you!

**Comment by leondutoit** [comment]
Great :)
