### ISSUE TITLE
OSError: Could not locate nacl lib

### ISSUE THREAD

**Issue by shahramb160** [unioslo/tsd-api-client#98]
Hi 
I tried to install tacl in NIRD and getting the following error. Anyone can help? 
```
[shahrab@login3-nird-tos SUMSTAT]$ tacl --guide config
Traceback (most recent call last):
  File "/nird/home/shahrab/.local/bin/tacl", line 5, in <module>
    from tsdapiclient.tacl import cli
  File "/nird/home/shahrab/.local/lib/python3.9/site-packages/tsdapiclient/tacl.py", line 25, in <module>
    from tsdapiclient.fileapi import (
  File "/nird/home/shahrab/.local/lib/python3.9/site-packages/tsdapiclient/fileapi.py", line 14, in <module>
    import libnacl.public
  File "/nird/home/shahrab/.local/lib/python3.9/site-packages/libnacl/__init__.py", line 83, in <module>
    nacl = _get_nacl()
  File "/nird/home/shahrab/.local/lib/python3.9/site-packages/libnacl/__init__.py", line 79, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.23, libsodium.so.18, libsodium.so.17, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4, 

```

**Comment by shahramb160** [comment]
Hi Erik,

Thank you very much. Just please let me know when the changes is implemented.


Best

Shahram

________________________________
